### ISSUE TITLE
new_lot_size in GetLotSizeAuto() causes invalid pointer access in 'EA31337.mq4' (4114,25) when debugging

### ISSUE THREAD

**Issue by kenorb** [EA31337/EA31337#103]
![](https://user-images.githubusercontent.com/40273435/52377066-ac24e380-2a5b-11e9-878a-ee817ede3c80.png)

_Originally posted by @soumsena in https://github.com/EA31337/EA31337/issues/102#issuecomment-461208576_

**Comment by kenorb** [comment]
@soumsena What do you've in line 4115, in my code it's the empty line. What errors do you get?

**Comment by kenorb** [comment]
@soumsena Can you post screenshot related to this line, what's the error exactly?

**Comment by soumsena** [comment]
@kenorb Thank you for replying. the issue is the same.
invalid pointer access in 'EA31337.mq4' (4114,25)

**Comment by soumsena** [comment]
![10](https://user-images.githubusercontent.com/40273435/52490326-6a5f7e80-2bbc-11e9-9464-6d895fe1067b.png)
![11](https://user-images.githubusercontent.com/40273435/52490330-6b90ab80-2bbc-11e9-8f3e-b9fe6a943fbc.png)
![13](https://user-images.githubusercontent.com/40273435/52490331-6b90ab80-2bbc-11e9-99e9-22c7243ebad3.png)

**Comment by soumsena** [comment]
when i read the file Trade.mqh and Chart.mqh, everything is correct. so i don't understand the isssue

**Comment by soumsena** [comment]
@kenorb , i changed  in the file Chart.mqh the function
 /*
    static uint TfToIndex(ENUM_TIMEFRAMES _tf) {
      _tf = (_tf == 0 || _tf == PERIOD_CURRENT) ? (ENUM_TIMEFRAMES) _Period : _tf;
      for (int i = 0; i < ArraySize(arr_tf); i++) {
        if (arr_tf[i] == _tf) {
          return (i);
        }
      }
      return (0);
    }
     */
To

 /**
     * Convert timeframe constant to index value.
     */
    
       static int TfToIndex(ENUM_TIMEFRAMES tf) {
       switch (tf) {
       case PERIOD_M1:  return M1;
       case PERIOD_M2:  return M2;
       case PERIOD_M3:  return M3;
       case PERIOD_M4:  return M4;
       case PERIOD_M5:  return M5;
       case PERIOD_M6:  return M6;
       case PERIOD_M10: return M10;
       case PERIOD_M12: return M12;
       case PERIOD_M15: return M15;
       case PERIOD_M20: return M20;
       case PERIOD_M30: return M30;
       case PERIOD_H1:  return H1;
       case PERIOD_H2:  return H2;
       case PERIOD_H3:  return H3;
       case PERIOD_H4:  return H4;
       case PERIOD_H6:  return H6;
       case PERIOD_H8:  return H8;
       case PERIOD_H12: return H12;
       case PERIOD_D1:  return D1;
       case PERIOD_W1:  return W1;
       case PERIOD_MN1: return MN1;
       case PERIOD_CURRENT: return 0;
       default            : return NULL;
       }
       }
     the function exited, but it was comment. i juste add  "case PERIOD_CURRENT: return 0;". It is OK for now

**Comment by kenorb** [comment]
`TfToIndex()` converts the given timeframe to array index, so M1 gets 0, M2 gets 1, and so on.
Not sure why this didn't work, but it needs some work.
By assigning `PERIOD_CURRENT` a zero, you most likely assigned M1, which is most likely incorrect.
But if it doesn't crash, that's fine for now, but it can produce some unexpected results.

I'll test that `TfToIndex()` function soon and provide the solution. Thanks for reporting.

**Comment by kenorb** [comment]
The issue has been fixed in 799fdd884292ddc438151e7cd981cfb760f02622 and in [064f69f6e050cce77c94e2ae3a02694086b6a2ca](https://github.com/EA31337/EA31337-classes/commit/064f69f6e050cce77c94e2ae3a02694086b6a2ca) (make sure to update `EA31337-classes` code base).

**Comment by kenorb** [comment]
However, I think the fix could caused some regression as per GH-106.

**Comment by soumsena** [comment]
yes is right, I just saw it
