### ISSUE TITLE
How to test strategies one by one?

### ISSUE THREAD

**Issue by soumsena** [EA31337/EA31337#107]
@kenorb, how can I test strategies one by one? I wanted to use EA31337-strategies folder

**Comment by kenorb** [comment]
Currently you need to do it manually, so by enabling each strategy manually and testing the params.
E.g. you enable RSI, then optimizing period, then applied price, then other settings.
It's very time consuming, as you've to think what params does what and what they're rely on. Basically you need to try with trial and error.

However, I'm working currently on the new method using Docker, but it's not ready yet and it'll take me few weeks to finish.

Check the [wiki pages](https://github.com/EA31337/EA31337/wiki), maybe you can find something useful, especially how you can backtest using Docker.
I'll update you when I'll have Docker optimization example ready.

**Comment by kenorb** [comment]
First try if backtesting using Docker works for you as per these steps: [Backtesting using Docker](https://github.com/EA31337/EA31337/wiki/Backtesting-using-Docker), so it's going to be easier for you to understand how to do optimization.

**Comment by soumsena** [comment]
ok, thx

**Comment by kenorb** [comment]
Update: For strategy optimization, I've implemented [GitHub Actions](https://github.com/EA31337/EA31337-Lite-optimization-tests/actions), you can check files in [`.github/workflows`](https://github.com/EA31337/EA31337-Lite-optimization-tests/tree/master/.github/workflows) how it's done. If you fork the repo, and edit relevant files, you can setup each strategy on your own.

**Comment by kenorb** [comment]
- [New release has been published](https://github.com/EA31337/EA31337/releases) where you can specific strategy on the given timeframe. It's reusing the existing EA31337-strategies repository.
- For [EA31337-strategies](https://github.com/EA31337/EA31337-strategies) repo it-self, each strategy has .mq4/.mq5 executable file which you can compile and run the test.
- There is also [EA31337-Libre](https://github.com/EA31337/EA31337-Libre) project which has been released where you can test each strategy one by one.

**Comment by kenorb** [comment]
Related: https://github.com/EA31337/EA31337/discussions/295
