### ISSUE TITLE
To use the files in the strategy folder in file EA31337.mql4

### ISSUE THREAD

**Issue by soumsena** [EA31337/EA31337#110]
@kenorb , Is it possible to use the files in the strategy folder in file EA31337.mql4, if YES, how can we do it???. thx

**Comment by kenorb** [comment]
@soumsena Can you clarify which strategy folder you mean?

**Comment by soumsena** [comment]
EA31337-strategies folder where all the strategies are inside

**Comment by soumsena** [comment]
https://github.com/EA31337/EA31337-strategies-old

**Comment by kenorb** [comment]
> https://github.com/EA31337/EA31337-strategies-old

This is the prototype repo for future refactoring. I've tried to do some refactoring towards that way, but it was a too drastic change and it didn't work out (too many repos was too difficult to manage). So this is kind of placeholder for future use, not all of these strategies are working, it's work in progress.
So currently I'm going to refactor code slowly to adopt these changes, but this most likely will end up in another form. So currently this folder is useless.

**Comment by soumsena** [comment]
o i ve understood. thx
