### ISSUE TITLE
Missing input values for AC strategy

### ISSUE THREAD

**Issue by soumsena** [EA31337/EA31337#111]
I wanted to know which ea-input file you are using. because the input file that is in the EA31337 / lite folder is different from the one that EA uses. it misses more field. for example
double AC1_MaxSpread = 6.0; // Max spread to trade for M1 (pips)
double AC5_MaxSpread = 7.0; // Max spread to trade for M5 (pips)
double AC15_MaxSpread = 8.0; // Max spread to trade for M15 (pips)
double AC30_MaxSpread = 10.0; // Max spread to trade for M30 (pips), 
the parameters of ADX, __Ichimoku_Parameters__, .......

**Comment by kenorb** [comment]
AC strategy is not implemented yet. Its trade function (`Trade_AC`) needs more coding, and some code changes in `UpdateIndicator()`.
So the AC values are internal (without `extern` keyword), that's why you don't see them, because they won't work currently.
It's going to be implemented soon.

**Comment by soumsena** [comment]
@kenorb , OK thx you

**Comment by soumsena** [comment]
what is the difference between Advanced and Rider

**Comment by kenorb** [comment]
> what is the difference between Advanced and Rider

Replied in GH-113

**Comment by kenorb** [comment]
This has been fixed in [v1.079](https://github.com/EA31337/EA31337/releases/tag/v1.079).
