### ISSUE TITLE
Results have been discarded as insignificant

### ISSUE THREAD

**Issue by soumsena** [EA31337/EA31337#114]
@kenorb, every time I try to do optimization, there is no information. when I look in the log, here is the massage that appears **There were 28 passes done during optimization, 28 results have been discarded as insignificant.** how can i fix that??? thx

**Comment by kenorb** [comment]
Insignificant result means with negative profit. It's good for filtering purposes, when you've many results with profit.
However, in the beginning of optimization, it's better to show insignificant results, so you know which results are better over other.
To do that, you right click on the Results tab, you should see the option to enable insignificant results. Then re-run the optimization test.

**Comment by soumsena** [comment]
@kenorb, Thanks you very much

**Comment by soumsena** [comment]
what are the parameters that you advise me to optimize????

**Comment by kenorb** [comment]
Have a look at [`EA31337-optimization-rules`](https://github.com/EA31337/EA31337-optimization-rules) repo, it has some rules to optimize [strategy specific params](https://github.com/EA31337/EA31337-optimization-rules/tree/master/Strategies) and other.

**Comment by kenorb** [comment]
To know which parameters should be optimized when, I think this is the task for some machine learning algorithm, as it's not easy to find out the right order or their dependencies (which params affects which).
I'm planning to simply the process, but it's not an easy task.
