### ISSUE TITLE
Do you have a config file that I can use?

### ISSUE THREAD

**Issue by soumsena** [EA31337/EA31337#129]
Hi Kenorb, how are you??? Can I have your  config file that you use please, because when I try to test with default settings file, I do not get the same results as the image. this is l'image

![](https://user-images.githubusercontent.com/266306/58390426-25573f00-8029-11e9-91fa-c97e1a7b34d9.gif)

**Comment by kenorb** [comment]
The image doesn't load. There is no special config, the results can vary depending on your setup, and how you're testing it. Each version tries to handle risk better. Please share more details how do you test it.

As the results can vary based on your broker's market parameters, especially the spread, lot sizes, account leverage and on the current market conditions.

**Comment by kenorb** [comment]
Btw. The test was performed using Docker setup (if that's what you're asking), steps can be found at: [Backtesting using Docker](https://github.com/EA31337/EA31337/wiki/Backtesting-using-Docker). But currently I've some issues forcing the lot size of 0.01, so the results can be different till the tester scripts are fixed. If you need more details, please let me know.

**Comment by soumsena** [comment]
thank you for your answer, I was talking about config file .set, because what I took in the folder EA31337-Lite-optimization-tests-master, does not give the same results as the image. so I thought it should have a second config file .set

**Comment by kenorb** [comment]
Above test result was using default settings from v1.077.

**Comment by kenorb** [comment]
New version has been released: [v1.079](https://github.com/EA31337/EA31337/releases/tag/v1.079). Should work much better without SET file, please use the default settings.
