### ISSUE TITLE
How to compile and backtest EA in Linux without using Docker?

### ISSUE THREAD

**Issue by codeitlikemiley** [EA31337/EA31337#132]
Hi i would like to ask if it is possible to do backtest/compile code without using docker?

May i know some of the requirements

just my hunch i think i will need wine to make this work.

I already have it , and a MT4 trader .exe software...

I dont wanna use docker since , it east up a lot of memory.

i always run out of memory since its only 8gb ram.

maybe using bare metal archlinux with all the required sofware can make it reduce the necessary ram to consume and use my gpu and processor at max capability.

Can you point me to the right direction thanks :)

**Comment by kenorb** [comment]
Yes, please check the steps at [Backtesting in MT4](https://github.com/EA31337/EA31337/wiki/Backtesting-in-MT4) (_Manual method_). These steps should be very easy to follow.

Basically, you need to download already converted FXT/HST files into your platform folder, then run the test as usual (the easiest way). Or you can download CSV files on your own (e.g. from the [FX-Data repos](https://github.com/FX-Data)), and convert it using a [`convert_csv_to_mt.py`](https://github.com/EA31337/FX-BT-Scripts) Python script (more time consuming method).
