### ISSUE TITLE
How to change leverage for backtesting?

### ISSUE THREAD

**Issue by codeitlikemiley** [EA31337/EA31337#133]
I wanna try other leverage like 1:2 , 1:5 or much more...
how can i set it?

**Comment by kenorb** [comment]
I don't think platform allows it to change in easy way. The workaround is to connect to broker which allows it to change. Once you connect, it reads the data from broker.

Without connecting to broker, I don't know how to achieve it yet.

I believe current broker's leverage is kept in `accounts.ini` file, but it's encrypted. Another workaround is to hack and patch the leverage in memory.

You can change it within [FXT binary file](https://github.com/EA31337/MT-Formats/blob/master/fxt-405-refined.mqh#L83):
```
   int               leverage;           // Account leverage (default: 100). Same as: AccountLeverage()
```

To try, you can try [`modify_mt_formats.py` Python script](https://github.com/EA31337/FX-BT-Scripts/blob/master/modify_mt_formats.py), but I don't think it's going to have any effect.

If you find some method which works, please let me know.

**Comment by kenorb** [comment]
Related posts:
- [Leverage at backtester?](https://www.mql5.com/en/forum/122162) (no solution)

**Comment by kenorb** [comment]
You have to use MetaTrader 5 platform instead which easily allows you to change the leverage for the test.
