### ISSUE TITLE
are you available at discord , telegram ?

### ISSUE THREAD

**Issue by codeitlikemiley** [EA31337/EA31337#134]
I would love to ask help  and questions , and i think this channel is inappropriate...

Hope you can share any discord or telegram or any platform.

that would be awesome :D

**Comment by kenorb** [comment]
Yes, you can join at Telegram group, link below.
[![](https://img.shields.io/badge/chat-Telegram-0088CC.svg?logo=telegram)](https://t.me/EA31337)
Or send me the private message at [@kenorb](https://t.me/kenorb).
