### ISSUE TITLE
Why backtests use a spread of 10 for EURUSD?

### ISSUE THREAD

**Issue by impulsecorp** [EA31337/EA31337#153]
For backtests, why do you use a spread of 10 for EURUSD, when most brokers have a spread less than 2?

**Comment by kenorb** [comment]
Do you mean 2 spread in pips or points? Spread 10 is equivalent to 1 pip for 5-digit symbol. If you mean 2 points, then it's equivalent to 0.2 spread in pips for 5-digit symbol.

There is no specific reason, apart of making the backtests more rigoristic, as I don't think most brokers have spread less than 2. Spread can vary, depending on the market conditions. Some brokers increase spreads when the market have increased volumes.

Making it 10 points when you optimize strategies, you forcing them to make some larger profits, not tiny. However, I could expand backtest results with 5 points as well.

----

In general, there are different type of brokers who offer either fixed, variable spreads or fractional pip pricing. With low spreads, comes higher commissions.

For example this chart from [forexchurch.com](https://www.forexchurch.com/forex-spreads) shows the following spread comparison:

<img width="311" alt="Screenshot 2019-07-14 at 17 57 45" src="https://user-images.githubusercontent.com/266306/61186761-e9bc1700-a660-11e9-8746-0c1de7784fe8.png">

Most if of I see above 1.0 pip (10 points).

--

Btw. If you know any good brokers which have spread less than 2 points (0.2 pips), please share.

**Comment by impulsecorp** [comment]
Sorry, I did not realize a spread of 10 points was 1 pip. Yes, using 10 points for it is very accurate, especially because you want that number to take slippage into account also.
