### ISSUE TITLE
Trade Context Busy in MT5

### ISSUE THREAD

**Issue by syhazvi** [EA31337/EA31337#155]
I am getting this    Error (4290): TradeAllowed: Trade context is temporary busy. When i try to backtest the EA on MT5.

**Comment by kenorb** [comment]
I haven't tested the code fully in MT4. When attempting to run it via Wine in MT5, it doesn't even start.
I'll have a look for this issue when I got the chance of running it.

**Comment by syhazvi** [comment]
Hi

On MT4 I get this

EA31337-Advanced-v1.078 USDJPY,M30: Error (1230): ExecuteOrder: Invalid stops. (err_code=130, sid=78)

EA31337-Advanced-v1.078 USDJPY,M30: Debug (1242): ExecuteOrder: OrderSend(USDJPY, SELL STOP, 0.01, 105.121000, 500, 104.609000, 105.109000, 'MFI15; 0.6 pips spread; sid: 78', 31415, 0, 255)

EA31337-Lite-v1.078 EURUSD,M30: Error (1230): ExecuteOrder: Invalid stops. (err_code=130, sid=42)

EA31337-Lite-v1.078 EURUSD,M30: Debug (1242): ExecuteOrder: OrderSend(EURUSD, SELL, 0.01, 1.121390, 500, 1.125400, 1.118400, 'CCI15; 0.8 pips spread; sid: 42', 31379, 0, 255)


No trades opened so far

Sent from Mail for Windows 10

**Comment by kenorb** [comment]
@syhazvi Fixed division by zero and trade context for MT4 in `master` branch.

**Comment by syhazvi** [comment]
Thanks

EA working on MT5 but can not control the number of Max orders per strategy

**Comment by kenorb** [comment]
> Thanks
> 
> EA working on MT5 but can not control the number of Max orders per strategy

Can you elaborate? You mean, you changing the param and doesn't take any effect?

**Comment by syhazvi** [comment]
Yes ,changing the parameter does not have any effect .

**Comment by kenorb** [comment]
MT5 issues has been fixed in #178.
You can test the new beta version by going to the [Release page](https://github.com/EA31337/EA31337/releases).
