### ISSUE TITLE
Error: ExecuteOrder: Unknown error. (err_code=4754)

### ISSUE THREAD

**Issue by kenorb** [EA31337/EA31337#156]
Related: #181

**Comment by syhazvi** [comment]
Getting these compile errors now

'ToString' - member function not defined	EA31337.mq4	588	65
implicit conversion from 'number' to 'string'	EA31337.mq4	588	65
'Order' - default constructor of class 'Order' is not defined	EA31337.mq4	1178	23
   see declaration of 'Order'	Order.mqh	61	7
'GetMarginRequired' - member function not defined	EA31337.mq4	4926	14
'GetMarginRequired' - member function not defined	EA31337.mq4	4928	74

**Comment by kenorb** [comment]
> Getting these compile errors now
> 
> 'ToString' - member function not defined	EA31337.mq4	588	65
> implicit conversion from 'number' to 'string'	EA31337.mq4	588	65
> 'Order' - default constructor of class 'Order' is not defined	EA31337.mq4	1178	23
> see declaration of 'Order'	Order.mqh	61	7
> 'GetMarginRequired' - member function not defined	EA31337.mq4	4926	14
> 'GetMarginRequired' - member function not defined	EA31337.mq4	4928	74

You need to update the submodules ([EA31337-classes](https://github.com/EA31337/EA31337-classes)) to update the changes. If you're using git, run: `git submodule update`.

**Comment by kenorb** [comment]
Fixed in #178.
