### ISSUE TITLE
Fix 'invalid pointer access' for SmartQueue in MT5

### ISSUE THREAD

**Issue by kenorb** [EA31337/EA31337#158]
- Branch: `v1.079-dev`
- Version: Advanced
- Platform: MT5

The commit f4eddf8abb791b9f337066b5e394358d48bbc8cb disables SmartQueueActive/OrderQueueProcess in MQL5, because of the crash (invalid pointer access).

Re-activate SmartQueue by re-enabling:
```
  if (SmartQueueActive && !order_placed && total_orders <= max_orders) {	  if (SmartQueueActive && !order_placed && total_orders <= max_orders) {
    order_placed &= OrderQueueProcess();	    order_placed &= OrderQueueProcess();
  }
```
then run historical test for Advanced, it crashes. It works fine in MT4.

**Comment by nseam** [comment]
Fix: https://github.com/EA31337/EA31337-classes/pull/60/commits/fbcf2db05f32ec2946b24a8efe56fccd607d19b4

**Comment by kenorb** [comment]
Fixed in GH-160.
