### ISSUE TITLE
How to use it with MT5

### ISSUE THREAD

**Issue by BillLeBraco** [EA31337/EA31337#161]
Hello, I'm a new user of MT5 and I want to try trading forex with EA. I found your github and your EA but when I add the file in Mql5 folder I don't see the EA in the navigator. Is there something special to do ? Someone can help me please ?

Best regards,

**Comment by kenorb** [comment]
The next release version should consist binary files to work on MT5.

Meanwhile you can try to compile the code, by changing `.mq4` extension into `.mq5`.

**Comment by BillLeBraco** [comment]
Thank you for your quick reply. Is it possible to contact you in private message ?

**Comment by kenorb** [comment]
Contact me on Telegram (@kenorb).

**Comment by adamwuyu** [comment]
Hi, may I ask when will the next release come? Or please tell me how to compile, thanks you so much!

**Comment by kenorb** [comment]
> Hi, may I ask when will the next release come?

Approximately in a month or two.

**Comment by kenorb** [comment]
[Beta release is ready for testing](https://github.com/EA31337/EA31337/releases/tag/v1.079-dev-beta).

**Comment by kenorb** [comment]
> Hi, may I ask when will the next release come?

The v1.079 version has been released at https://github.com/EA31337/EA31337/releases/tag/v1.079 with support for MT5.
