### ISSUE TITLE
Make some big files more organized

### ISSUE THREAD

**Issue by videni** [EA31337/EA31337#169]
I really like this project, can you make some big files more organized? 

The [src/EA31337.mq5](https://github.com/EA31337/EA31337/blob/master/src/EA31337.mq5) and  `src/EA31337.mq4` are more than 4000 lines ,  it is so bigger, so difficult  to understand. maybe you can seperate it into different files based on their functions instead of huge files, the ` separation of concerns` pattern might be helpful.

**Comment by kenorb** [comment]
> `src/EA31337.mq4` are more than 4000 lines , it is so bigger, so difficult to understand. maybe you can seperate it into different files based on their functions instead of huge files.

That's the plan, the separation started already, and a lot of code has been already moved to [EA31337-classes](https://github.com/EA31337/EA31337-classes) (a framework), and there is still a lot of work to do.

**Comment by videni** [comment]
I see,  anything we can help?  maybe you can create some todos, and add some brief description about each one.

**Comment by kenorb** [comment]
> I see, anything we can help? maybe you can create some todos, and add some brief description about each one.

If you think anything needs improvements, you think of some useful features, feel free to create a ticket for each separate part.

**Comment by kenorb** [comment]
Large files has been finally organized.
https://github.com/EA31337/EA31337/releases
