### ISSUE TITLE
Error (1109): ExecuteOrder: Unknown error. (err_code=4753, sid=114)

### ISSUE THREAD

**Issue by javierchacon262** [EA31337/EA31337#177]
Greetings Sr. I have a little problem when backtesting the EA and it is what you are reading in the title, i have not changed any parameter but the error continues appearing every time the EA tries to place an order, this means that it does not place any order in all the backtest. i'll submit here part of the backtesting journal log. PLEASE HELP, there no good documentation about this error around internet and honestly i'm not very used to mql5.

- 2019.11.25 13:24:15.846	2019.01.02 21:00:00   Debug (1121): ExecuteOrder: OrderSend(EURUSD, SELL, 0.04, 1.132730, 500, 1.136730, 1.127500, 'WPR15; 1.7 pips spread; sid: 114', 31451, 0, 255)

- 2019.11.25 13:24:15.846	2019.01.02 21:00:00   Debug (1122): ExecuteOrder: ACCOUNT: Time: 2019.01.02 21:00:00; Balance: $2000.00; Equity: $2000.00; Credit: $0.00; Margin Used/Free: $0.00/$2000.00; Risk: 1.0;

- 2019.11.25 13:24:15.846	2019.01.02 21:00:00   Debug (1123): ExecuteOrder: MARKET: Symbol: EURUSD; Ask: 1.13290; Bid: 1.13273; Spread: 17pts (1.70 pips);

- 2019.11.25 13:24:15.904	2019.01.02 21:15:00   Error (1109): ExecuteOrder: Unknown error. (err_code=4753, sid=114)

(This repeats every time...
[20191125.log](https://github.com/EA31337/EA31337/files/3888091/20191125.log)
)

**Comment by kenorb** [comment]
Thanks for the reporting and the log file.

Error 4753 is related to [_Position not found_](https://www.mql5.com/en/docs/constants/errorswarnings/errorcodes). As per this [forum](https://www.mql5.com/en/forum/214219):

> It seems to me that if PositionSelect(symbol) returns false, it ALSO generates ERROR 4753.

I'll try to reproduce issue when I can.

**Comment by javierchacon262** [comment]
That's the fun thing, i've been looking in your code you do not use PositionSelect(). Do you think maybe the issue is because i'm using MT5?

**Comment by kenorb** [comment]
> That's the fun thing, i've been looking in your code you do not use PositionSelect(). Do you think maybe the issue is because i'm using MT5?

I think it's [OrderSelect](https://www.mql5.com/en/docs/trading/orderselect) used instead. Last time when I've tested MQL5 version it was opening trades. But in general [`Order::OrderSend()`](https://github.com/EA31337/EA31337-classes/blob/cbb6c27b0501b867ef18166ba3def8f085107690/Order.mqh#L534) is used to open orders.

I've tested few days ago simpler version of EA: [EA31337 Libre](https://github.com/EA31337/EA31337-Libre) and it was opening trades in MT5 during backtesting fine, using the same framework. Although, I've added few extra fixes.

The issue could be broker-specific, like certain filling mode which could be not yet implemented. For example, see: GH-163 (`ORDER_FILLING_IOC`). I'll test XM broker soon, and see if I can reproduce it.

**Comment by javierchacon262** [comment]
Oh, now that you mention that, i do use XM as my broker. Maybe that's the problem

**Comment by kenorb** [comment]
Support for IOC type filling potentially fixed in 71811175d2621d28b2ca153b759682b4fce399f0

[Relevant line](https://github.com/EA31337/EA31337-classes/commit/71811175d2621d28b2ca153b759682b4fce399f0#diff-82e4bd8a8e6b259efbf2e69cb185a84fR653):
```
_request.type_filling = GetOrderFilling(_symbol);
```

I'll integrate it into `master` branch soon.

**Comment by kenorb** [comment]
Fixed potentially in #163 and #178. The code fixes are now in `master` branch.
