### ISSUE TITLE
Order confusion of some functions in MT4 vs MT5

### ISSUE THREAD

**Issue by lancesye** [EA31337/EA31337#181]
Hai kenorb! Thank you very much for sharing your source code! I found there were some bugs in mql5 version. Firstly I  can't control the Max orders parameter.

The function `GetTotalOrders() `:
```
Order::OrderSelect(order, SELECT_BY_POS, MODE_TRADES) && OrderSymbol() == Symbol()
```

In `Order.mqh`, it would return error when want to select a position using `OrderGetTicket()`.

I think you confusion some function in mql5 and mql4 . When the order is dealed, it become a position.

If you want to get the open positions information, you should use `PositionSelect()` or `PositionGetTicket()` or `PositionGetSymbol()` to selects the position first for further working with it using functions `PositionGetDouble`, `PositionGetInteger`, `PositionGetString`.

In Order.mqh, many `OrderSelect` function and get Order information function should Change to corresponding Position function. In mql4 they are ok. For these reasons, some order information didn't display  in the chart.

**Comment by kenorb** [comment]
Thanks for the bug report, this is going to be fixed soon in the codebase.

There are already some fixes in [EA31337-classes](https://github.com/EA31337/EA31337-classes), but it'll take some time till they're going to be integrated into this repository.

Related PRs:

- https://github.com/EA31337/EA31337-classes/pull/145
- https://github.com/EA31337/EA31337-classes/pull/152
- https://github.com/EA31337/EA31337-classes/pull/154

**Comment by kenorb** [comment]
Fixed in `master` branch (GH-191).

**Comment by kenorb** [comment]
You can test compiled beta version at [Releases page](https://github.com/EA31337/EA31337/releases).
