### ISSUE TITLE
How can I use only one indicator?

### ISSUE THREAD

**Issue by adamwuyu** [EA31337/EA31337#187]
There are many indicators. If I only want to use one of them. How can I disable others?

**Comment by kenorb** [comment]
In the v1.078 and v1.079/master versions (not released yet), you need to disable all "*_Active_Tf" parameters and enable the one which you require.

Each strategy has its own "Active_Tf" which controls activated timeframes, e.g. 0 is off, M1=1, M5=2, M15=4, M30=8, H1=16, H2=32 and so on.
