### ISSUE TITLE
Zero divide in Market.mqh (181,53) when running on stock market

### ISSUE THREAD

**Issue by kenorb** [EA31337/EA31337#219]
- Tag: v1.079
- Symbol: WINQ20
- Tf: M1
- Related: https://github.com/EA31337/EA31337-classes/issues/301

![image](https://user-images.githubusercontent.com/266306/88592922-ab6c7c80-d056-11ea-9365-00390a963ef4.png)

> I see a pattern, I tried to test the EA on other indexes and I couldn't, they are: HK50 and US30.

**Comment by psynando012** [comment]
is it not necessary to change something in the market.mqh file?
