### ISSUE TITLE
Calculate equity per EA

### ISSUE THREAD

**Issue by kenorb** [EA31337/EA31337#222]
Related: https://github.com/EA31337/EA31337-classes/issues/311

**Comment by enjoysmath** [comment]
Is this enhancement ready for download?   What I need is to run on multiplie currencies and multiple time frames (ideally) from within a single EA .ex5.  What is the status on being able to do that?

**Comment by kenorb** [comment]
> Is this enhancement ready for download?

You can use tasks with condition related to Equity (like above or below 1%), but it's currently is using the whole account.

This feature is to calculate equity per each strategy, so it doesn't affect any other trades (such as manual trades or other EAs). So it only calculates it for the trades that is managing.

> What I need is to run on multiplie currencies and multiple time frames (ideally) from within a single EA .ex5. What is the status on being able to do that?

You can run multiple timeframes, but not currencies (yet). Trading multiple currencies is going to be added in the near future.
This can be achieved, but few code refactors are needed.

**Comment by enjoysmath** [comment]
How do you enable Advanced mode (it's in Lite by default), so that I can
use those task conditions?

Thank you!

**Comment by enjoysmath** [comment]
> > Is this enhancement ready for download?
> 
> You can use tasks with condition related to Equity (like above or below 1%), but it's currently is using the whole account.
> 
> This feature is to calculate equity per each strategy, so it doesn't affect any other trades (such as manual trades or other EAs). So it only calculates it for the trades that is managing.
> 
> > What I need is to run on multiplie currencies and multiple time frames (ideally) from within a single EA .ex5. What is the status on being able to do that?
> 
> You can run multiple timeframes, but not multiple currencies (yet). Trading multiple currencies is going to be added in the near future.
> This can be achieved, but few code refactors are needed.

What can I do to help you refactor the code and add that feature?  I know C++ well enough to hack on the EA, but I don't want to iterrupt your coding chi.

**Comment by kenorb** [comment]
> How do you enable Advanced mode (it's in Lite by default), so that I can use those task conditions?

https://github.com/EA31337/EA31337/issues/283

**Comment by kenorb** [comment]
> What can I do to help you refactor the code and add that feature?

It's going to take longer to explain, than implement it. So I'm going to prioritize it for the next release.

> I know C++ well enough to hack on the EA, but I don't want to iterrupt your coding chi.

New ideas on new strategies or their signal conditions could be helpful.

> I have $159 in paypal I could send to you if that would help.

You can sponsor some tickets/issues at issuehunt.io if you like, but it's up to you.

> It would also be nice to know how to code on the EA myself, if you could teach.

- Working on git submodules is a good start (as classes and each strategy has their own).
- Debugger is your friend (and breakpoints and step-by-step debugging useful to understand the code).
- I may create some videos in near future related to coding, but the code changes so rapidly, so it'll become outdated too soon. Creating such video and post-processing it could take a day, which can interrupt a coding chi and less code is going to be produced. When the code changes become calmer (finalized more), then I'm going to do it.
