### ISSUE TITLE
test result is different with release page test result

### ISSUE THREAD

**Issue by atreeyang** [EA31337/EA31337#239]
I run the command : docker run ea31337/ea-tester:EURUSD-2019-DS run_backtest -v -e https://github.com/EA31337/EA31337/releases/download/v1.080/EA31337-Lite-v1.080.ex4
the result is lost 892 usd.
========

Currency pair symbol:                       EURUSD
Initial deposit:                            10000.00 USD
Total net profit:                           -892.65 USD
Gross profit:                               1791.46 USD
Gross loss:                                 2684.11 USD
Absolute drawdown:                          913.08 USD
Maximal drawdown:                           913.1 USD (9.1%)
Relative drawdown:                          (9.1%) 913.1 USD
Profit factor:                              0.67
Expected payoff:                            -6.47
Trades total                                138
Short positions (won %):                    91 (25.3%)
Long positions (won %):                     47 (44.7%)
Profit trades (% of total):                 44 (31.9%)
Loss trades (% of total):                   94 (68.1%)
Largest profit trade:                       195.99
Largest loss trade:                         -53.67
Average profit trade:                       40.71
Average loss trade:                         -28.55
Average consecutive wins:                   2.00
Average consecutive losses:                 4.00
Maximum consecutive wins (profit in money): 4 (259.29)
Maximum consecutive losses (loss in money): 11 (-314.83)
Maximal consecutive profit (count of wins): 259.29 (4)
Maximal consecutive loss (count of losses): 314.83 (11)
Modelling quality:                          89.96%

**Comment by kenorb** [comment]
You need to specify the whole year by `-m 1-12` and ideally the timeframe for more accuracy (e.g. `-T M1`). I'm going to re-run v1.080 and let you know the exact configuration.

**Comment by kenorb** [comment]
The detailed backtest results for v1.80 can be found at:

- Lite: bd60bbc07ac3e4c08fa8b157a8d6b7f30709a47b (based on 008c0758b7d6c04060365efd017189b953986980 commit)
- Advanced: cf3bc8f49709b444fdc03f9148ea5bd74c62a403 (based on 008c0758b7d6c04060365efd017189b953986980 commit)
- Rider: 2b100879d9c787ec4ebee21b4b9ef7a7e938455f (based on 008c0758b7d6c04060365efd017189b953986980 commit)

**Comment by SinclairSaratov** [comment]
Que tal negociar XAU/USD com este algoritmo?
![IMG-20220120-WA0005](https://user-images.githubusercontent.com/92382819/150415117-013ab242-7eea-4a9d-b60c-cbe7129f6306.jpg)


https://github.com/SinclairSaratov/binarybot_perfect/issues/2#issue-1109715150

**Comment by kenorb** [comment]
> Que tal negociar XAU/USD com este algoritmo? ![IMG-20220120-WA0005](https://user-images.githubusercontent.com/92382819/150415117-013ab242-7eea-4a9d-b60c-cbe7129f6306.jpg)

Please raise a new question in the Discussion.

**Comment by kenorb** [comment]
Since v2.001 release, tests are done using MetaTrader 5 platform which you can find at https://github.com/orgs/EA31337/discussions/categories/releases
Using Docker tester and MT4 has some disadvantages and the results are sometimes unpredictable and it's difficult to find the reason. Also different slight changes such as different broker, or spread, or other configuration can result in different results. So at this point I won't be able to compare the specific results, as a lot of changed since then.
You can download the latest v2.013.1 version and compare the results in MT5 posted at https://github.com/orgs/EA31337/discussions/373 using MetaQuotes Demo, you should see the same results.
