### ISSUE TITLE
OrderClose error 4108

### ISSUE THREAD

**Issue by kenorb** [EA31337/EA31337#243]
> ERROR: Trade::OrdersCloseViaCmd:569: Error while closing order!; Code: 10011

> unknown ticket 28 for OrderClose function

> OrderClose error 4108

- Build: [1946986531](https://github.com/EA31337/EA31337/runs/1946986531?check_suite_focus=true#step:4:3070).
- Refs: https://github.com/EA31337/EA31337-classes/issues/476

**Comment by imunisasi** [comment]
EA31337-Lite-v2.000 (EURUSD,M1)
ERROR: Trade::OrdersCloseViaCmd:569: Error while closing order!; Code: 10013
