### ISSUE TITLE
Net profit is negative but strategies are profitable?

### ISSUE THREAD

**Issue by chrisdk2015** [EA31337/EA31337#26]
This is for v1.075.

See report. Set file attached.

Total net profit:                           -1733.46 USD

However sum of net profit from Bands M1 + M5 is 207.48 + 415.90  = 623.38 USD

Is this a bug or have I misunderstood something?

[AUDNZD-2000USD-2014.01.02-2015.12.31-3spread-(2)-M30-report.txt](https://github.com/EA31337/EA31337/files/2008310/AUDNZD-2000USD-2014.01.02-2015.12.31-3spread-.2.-M30-report.txt)

[EA31337-1.075-audnzd_bands.txt](https://github.com/EA31337/EA31337/files/2008305/EA31337-1.075-audnzd_bands.txt)

**Comment by chrisdk2015** [comment]
I think it is a problem with the historical data, but maybe it triggers a bug in the EA.

**Comment by kenorb** [comment]
Good catch. I'm assuming you didn't run any other EAs? As I think profits aren't calculated based on the magic numbers, but all trades.

The logic of summary is in [`SummaryReport` class](https://github.com/EA31337/EA31337-classes/blob/637060d10a39c948b8504b98a4492b0706d54af5/SummaryReport.mqh).

The trade number seems to be matching.

```
Strategies: Active strategies: 2
Short positions (won %):                    4401 (1.4%)
Long positions (won %):                     24746 (2.1%)
# 4401+24746=29147
--
Profit trades (% of total):                 572 (2.0%)
Loss trades (% of total):                   28575 (98.0%)
# 572+28575=29147
--
Total orders: 11544 (Won: 73.0% [8429] / Loss: 27.0% [3115]) - Bands M1
Total orders: 17603 (Won: 81.2% [14292] / Loss: 18.8% [3311]) - Bands M5
# 8429(won)+3115(loss)+14292(won)+3311(loss)=29147
# 11544(total)+17603(total)=29147
```

Notes:
- The spread is as low as 3 points, I'm not sure if spread difference could be responsible for it (see below).
- Profit trades (572) doesn't match with win trades (8429+14292=22721), possibly profit trades are [calculated](https://github.com/EA31337/EA31337-classes/blob/637060d10a39c948b8504b98a4492b0706d54af5/SummaryReport.mqh#L158) after the commision.

'Total net profit' is `summary_profit` which is calculated for every order in history as:

    profit = Order::OrderProfit() + Order::OrderCommission() + Order::OrderSwap();

So I think given the large number of trades, it's possibly related to [`OrderCommission`](https://docs.mql4.com/trading/ordercommission) and [`OrderSwap`](https://docs.mql4.com/trading/orderswap). This needs to be tested, probably by adding values for commision and swaps.

    Swap specification for AUDNZD: Mode: 0, Long/buy order value: -2.3, Short/sell order value: -3.3

So I think the trades were profitable in overall without commission, but they weren't profitable including broker commission and swaps.

**Comment by chrisdk2015** [comment]
Ran only this EA, not others (not sure if you can other EAs in the strategy tester).

But yes, it must be the commissions and swap that make the net profit negative.

**Comment by kenorb** [comment]
The report file functionality has been removed from the newest v2.000 [release](https://github.com/EA31337/EA31337/releases). It's going to be re-done from scratch.
So I'm going to close it, as it's no longer relevant.
