### ISSUE TITLE
Risk margin doesn't seems to work

### ISSUE THREAD

**Issue by kenorb** [EA31337/EA31337#277]
EA_Risk_MarginMax doesn't seems to take any effect.

**Comment by enjoysmath** [comment]
I think it's not working when LotSize = 0 (auto), but working when you set a nonzero value or optimize on a range of values  (at least when I'm backtesting).

**Comment by kenorb** [comment]
Fixed in 226c58a30e7d4352ede2cbdf0b0f4d924d885745 and https://github.com/EA31337/EA31337-classes/commit/15a06b2523e282011237a3bbe1ed86806a6cc1f5.

It's going to be included in the next release.

**Comment by enjoysmath** [comment]
> Fixed in [226c58a](https://github.com/EA31337/EA31337/commit/226c58a30e7d4352ede2cbdf0b0f4d924d885745) and [EA31337/EA31337-classes@15a06b2](https://github.com/EA31337/EA31337-classes/commit/15a06b2523e282011237a3bbe1ed86806a6cc1f5).
> 
> It's going to be included in the next release.

How do I get that update before the next release date?

**Comment by kenorb** [comment]
> How do I get that update before the next release date?

You need to [compile](https://github.com/EA31337/EA31337/wiki/Compilation) this project using `2.006-dev` branch.

**Comment by kenorb** [comment]
> How do I get that update before the next release date?

Alternatively download the binaries (Artifacts) from this build: [1198240057](https://github.com/EA31337/EA31337/actions/runs/1198240057).

**Comment by kenorb** [comment]
Actually from this one: [1199614433](https://github.com/EA31337/EA31337/actions/runs/1199614433), because the param was not exposed yet.

**Comment by enjoysmath** [comment]
> > How do I get that update before the next release date?
> 
> You need to [compile](https://github.com/EA31337/EA31337/wiki/Compilation) this project by checking out `2.006-dev` branch.

So this dev branch has the code change that fixes the above issue?

**Comment by kenorb** [comment]
> > > How do I get that update before the next release date?
> > 
> > 
> > You need to [compile](https://github.com/EA31337/EA31337/wiki/Compilation) this project by checking out `2.006-dev` branch.
> 
> So this dev branch has the code change that fixes the above issue?

Yes.

**Comment by enjoysmath** [comment]
> > How do I get that update before the next release date?
> 
> You need to [compile](https://github.com/EA31337/EA31337/wiki/Compilation) this project by checking out `2.006-dev` branch.

![image](https://user-images.githubusercontent.com/1606391/132071868-decfc4ca-a43d-466d-b2dd-9b96e5fddd88.png)

I checked out master last night.  Currently I don't see 2.006-dev in there, so what do I do?

**Comment by kenorb** [comment]
> I checked out master last night. Currently I don't see 2.006-dev in there, so what do I do?

You need to fetch from origin (`git fetch origin`).

**Comment by enjoysmath** [comment]
> > I checked out master last night. Currently I don't see 2.006-dev in there, so what do I do?
> 
> You need to fetch from origin (`git fetch origin`) to update the list, not sure about GUI.

I did ta get fetch, stashed my (unintended) changes, and then did a git checkout of 2.006-dev and compiled and I'm getting:

```
'Set' - no one of the overloads can be applied to the function call	EA31337.mq5	241	6
could be one of 2 function(s)	EA31337.mq5	241	6
   void EA::Set(ENUM_EA_PARAM_PROP,T)	EA.mqh	127	8
   void EA::Set(ENUM_STRATEGY_PARAM,T)	EA.mqh	135	8
```


![image](https://user-images.githubusercontent.com/1606391/132072464-85f98e47-9d7d-421a-a5f8-8b50646d2091.png)

**Comment by kenorb** [comment]
You need to update classes as well (it's a submodule).
git submodule update
Or go to src/include/classes
And pull from dev2 I think.

**Comment by enjoysmath** [comment]
> You need to update classes as well (it's a submodule).
> Try to run: git submodule update
> Or go to src/include/classes
> And pull from dev2 branch I think.

Thank you, I didn't know about that.  It's compiling now!

**Comment by enjoysmath** [comment]
I don't believe this bug is fixed.  I set Risk Margin to 10% and with Lots = 0, the drawdown stays below 1%.  Conversely,  when you try to optimize on a range of Lots, it seems to ignore a Risk Margin of 5% (what I need).

**Comment by kenorb** [comment]
> I don't believe this bug is fixed. I set Risk Margin to 10% and with Lots = 0, the drawdown stays below 1%. Conversely, when you try to optimize on a range of Lots, it seems to ignore a Risk Margin of 5% (what I need).

When Risk Margin is set to 10%, it should allow drawdown of around 10%.

Once Trade instance got the param value set, then this logic applies:
https://github.com/EA31337/EA31337-classes/blob/v2.005/Trade.mqh#L1249-L1251

**Comment by kenorb** [comment]
Fixed in GH-288.

Basically when EA's Risk Margin is set to 1%, it'll allow only margin to be used in 1%, then it won't open new trades, but it can still go below 1%. Below optimization test with Rider (DD is lower with Risk Margin being smaller).

![image](https://user-images.githubusercontent.com/266306/132772155-9d4a4458-f5e2-4724-aaa2-8a42aebd5113.png)
