### ISSUE TITLE
New week detection

### ISSUE THREAD

**Issue by hrdrq** [EA31337/EA31337#337]
In the [source code](https://github.com/EA31337/EA31337-classes/blob/master/DateTime.mqh#L116-L119), I think the if statement is true when the day changes, not only when new week starts.
For example, when the day changes from Monday to Tuesday, the value changes from `1` to `2`, but it's the same week.

**Comment by kenorb** [comment]
Addressed in https://github.com/EA31337/EA31337-classes/pull/650

**Comment by kenorb** [comment]
https://github.com/EA31337/EA31337/releases/tag/v2.011
