### ISSUE TITLE
TFM value for Every tick

### ISSUE THREAD

**Issue by jribault** [EA31337/EA31337#339]
Hi,

In the documentation we can see that "when optimizing by using Every tick modelling, you can pick 7 (ticks at peak)" but if I choose 7 I don't have any trade regardless of the other settings ... What did I miss ?

My goal is to try to find a scalping strategy, with lot of trades.

I'm using the last Advanced release (v2.010)

**Comment by kenorb** [comment]
The Signal tick filter set to 7 (1+2+4) is the combinations of the following 3 values:

- 1: ticks on every each minute
- 2:  low and high ticks of the bar
- 4: peak prices of each minute

When you're using positive values, you're using AND operation and these options are most likely exclusive. To use with the OR operation (1 or 2 or 4), you've to use negative value: -7.

In the meantime, please try it in v2.013 which is going to be released anytime soon, some things has been improved in general. The tick logic is going to be improved in the further versions.
