### ISSUE TITLE
Compiling error: "resource file 'indicators-other\Oscillator\SVE_Bollinger_Bands.ex4' not found	EA31337.mq4	14	11"

### ISSUE THREAD

**Issue by alteverest** [EA31337/EA31337#342]
Can´t figure out why this resource cannot be compiled. Cloning of the master repository was successful. No further errors

**Comment by kenorb** [comment]
MT platform has problems compiling dependency files. You need to compile these files manually one by one. To compile them, you also need to clone [EA31337-classes](https://github.com/EA31337/EA31337-classes) repo into your `Includes/`

**Comment by alteverest** [comment]
That worked, thanks. 
The https://github.com/EA31337/EA31337-classes repo is being saved as "EA31337-classes-master" so to compile I had to rename the folder  to "EA31337-classes"
