### ISSUE TITLE
Unable to compile following the compilation document

### ISSUE THREAD

**Issue by videni** [EA31337/EA31337#343]
```
git clone --recursive https://github.com/EA31337/EA31337  MT5/MQL5/Experts
ln -s EA31337/src/include/classes  MT5/MQL5/Include
```

Then  compile `/src/EA31337.mq5` using MetaEditor5.

I got following error
![image](https://user-images.githubusercontent.com/4058341/183241510-04cb725a-39c1-4710-86c5-e61d256af391.png)

**Comment by kenorb** [comment]
I think it's a MT5 platform issue. It's finding the right path for indicator .mq5 files, but it got problem compiling it, despite you've solved the dependencies with includes. My theory is that MT5 has problems finding where the Include/ folder is for each file.
In MT4 that kind of dependency compiling works fine.

As for the workaround, you've to open each indicator file and compile them one by one.

Related: GH-342.
