### ISSUE TITLE
Can't open include file from classes

### ISSUE THREAD

**Issue by 1290726334** [EA31337/EA31337#344]
The project could not be imported correctly?
![image](https://user-images.githubusercontent.com/16836773/185032272-0ac4f9d4-ae1e-4b27-9196-2e46aac48b84.png)
Hoping for help

**Comment by kenorb** [comment]
If you've downloaded a ZIP file from the repository, you're missing classes dependencies which are part of Git submodule.

Ideally you should use Git to clone the repository recursively.

E.g.

    git clone --recursive https://github.com/EA31337/EA31337

Or use Git Gui.

Check [Compilation page](https://github.com/EA31337/EA31337/wiki/Compilation) for more details.
