### ISSUE TITLE
Error Compiling: EA31337\src\include\classes\Array.mqh

### ISSUE THREAD

**Issue by ianmackers** [EA31337/EA31337#345]
I've had to go through and adapt the "indicators-other" #include locations to get the individual indicators to compile (similar issues experienced by others), but am getting one final error in the "EA31337\src\include\classes\Array.mqh" file in MT5 (Build 3265):

-> 'array' - constant variable cannot be passed as reference

![image](https://user-images.githubusercontent.com/114882727/200140782-594a5733-984f-4c72-b44a-fe6998d60208.png)

![image](https://user-images.githubusercontent.com/114882727/200140770-47b53db6-711a-4b57-b107-1427167a1499.png)

Any assistance would be greatly appreciated.

**Comment by kenorb** [comment]
> For a quick fix:
> 
> in `EA31337-classes/Array.mqh` line 756
> 
> search for a `static int ArraySize(const ARRAY_REF(X, array)) {` and remove const word.

Fix pending in https://github.com/EA31337/EA31337-classes/pull/660

Related issue: https://github.com/EA31337/EA31337-classes/issues/661

**Comment by kenorb** [comment]
Fixed in GH-338.
