### ISSUE TITLE
EA is not placing any trades but is simply just in initializing

### ISSUE THREAD

**Issue by Manfox177** [EA31337/EA31337#347]
![Screenshot](https://user-images.githubusercontent.com/72307123/207708152-b660ee45-6bd0-4ff0-9bb8-0e41de0ddb05.jpg)
Here is my terminal looks like the EA is not placing any trades but is simply just in initializing
And in the experts tab it keeps on saying this 
2022.12.14 20:35:50.189	EA31337-Lite-v2.010 (EURUSD,M5)	EA31337 Lite v2.010 (https://github.com/EA31337) initializing...
I followed the installation guide properly
Am using FBS by the way

**Comment by kenorb** [comment]
Screenshot showing account dump looks like it's working. The initial message usually waits for the new candles, then it shows the screen that you've right now.

Maybe you've to wait now a bit longer to see any trades.

**Comment by kenorb** [comment]
[New version released](https://github.com/EA31337/EA31337/releases), you may try it as well. I hope the problem is solved now.

**Comment by Manfox177** [comment]
Ok Thanks
