### ISSUE TITLE
Strategy Filter issue

### ISSUE THREAD

**Issue by 5oclockshadow** [EA31337/EA31337#358]
Hey guys, Thanks so much for the work ive learned alot... When in advanced mode im not seeing the strategy filter as defined here:
Signal strategy filter (int) - Sets a strategy filter for additional signal verification.

    0 - disabled
    1 - on multiple signals per timestamp, only first is processed
    2 - minute-based strategies can only open trades on confirmed signal from any of hour-based strategies

As Well as your Equity close tasks don't seem to work?! Equity>2 nor equity>5 worked... Have not tested others
![TesterGraphReport2023 06 05](https://github.com/EA31337/EA31337/assets/71989937/8fb4cf46-9818-471f-9486-5b6807e9479c)

**Comment by kenorb** [comment]
Fixed in 56525cb80a89132cc1b4fe3ab71d91f603ecc307.
