### ISSUE TITLE
Text on strategy filter parameter is wrong

### ISSUE THREAD

**Issue by francobritannique** [EA31337/EA31337#380]
In the text for the strategy filter parameter for Advanced and Rider, it includes the text “64=H4” when in fact 64=H3.

**Comment by kenorb** [comment]
You're right, I'll correct it in the next minor release.
Another issue is, that platform cuts the description at some point due to length, so not all values can be listed.
This could be moved to separate textfield, but it'll just take unnecessary extra space.
