### ISSUE TITLE
v1.080 cannot compile under MQL5

### ISSUE THREAD

**Issue by mavidelisi** [EA31337/EA31337#419]
Hi kenorb , i cant compile v1.080 on metattrader 5 . i am stuck. how can i compile please ? i am using metatrader 5  v5.00 build 4540.

I am using all versions of your software. I get help from each one. The v1.080 version is the most suitable and logical for me, but I cannot compile it. I would be glad if you could help me with this.

**Comment by kenorb** [comment]
Can you post what errors do you have?
v1.080 is a little behind and they change syntax in MQL all the time, so potentially MQL broke it, you need to fix the code manually.

**Comment by mavidelisi** [comment]
> Can you post what errors do you have? v1.080 is a little behind and they change syntax in MQL all the time, so potentially MQL broke it, you need to fix the code manually.

Hi Kenorb. Thanks for answers. 
I'm adding a screenshot of the error I encountered here.

![Screenshot 2024-09-18 081900](https://github.com/user-attachments/assets/0ddb2168-8152-4bef-ba48-da28cfab2bbd)

**Comment by kenorb** [comment]
The code was working previously at the time of release, so I've checked, and the errors were related to MQL language syntax changes, which they (MQL devs) change all the time and the code can break.

I've fixed it and released new minor tag at [`v1.080.1`](https://github.com/EA31337/EA31337/releases/tag/v1.080.1).

I've tested it by cloning as per below and it compiles now:
```
git clone --branch v1.080.1 --recurse-submodules https://github.com/EA31337/EA31337.git EA31337-v1080
```

The old code could still have some bugs, and it's minimally maintained. So if you'll get into more problems, please use the recent code which have several fixes.

**Comment by mavidelisi** [comment]
Thank you very much

**Comment by mavidelisi** [comment]
hello kenorb; I tested the robot, there is no problem in opening transactions and choosing strategies, but I think there is a problem in the conditions/actions section. Because as an example from the conditions/actions parameters; when you get a profit higher than 1 percent, close all of them, or close all transactions after 120 hours, or close transactions at the end of the day.. as. i'm having trouble closing processes. "CloseOrder: Error: Ticket: 542; Error: Unknown error." I encounter errors in the form of. There is no problem with metatrader 4, but I am having problems closing transactions on metatrader 5. Do you have a chance to check it out? 

Thank you.
