### ISSUE TITLE
Balance 1000 EUR calculates lot size 0.08 while on balance 1739 USD the calculated lot size is 0.01

### ISSUE THREAD

**Issue by chrisdk2015** [EA31337/EA31337#50]
For version 1.072 + default preset (EURUSD).

What can I provide to find the bug?

**Comment by kenorb** [comment]
Can you paste the initial lines from the startup? Or lines from the report file which are mentioning balance and calculated lot size?

**Comment by chrisdk2015** [comment]
This is for EUR 1000, now it calculates lot size 0.11 (0.07 in the display on the chart).

[lot_size_report.txt](https://github.com/EA31337/EA31337/files/2026355/lot_size_report.txt)

is this enough?

Boosting is enabled, this is a new account just started today to test this. The 0.08 lot size was a different account also started today.

**Comment by chrisdk2015** [comment]
This is for the account that calculates 0.01 lot 

[lot_size_report_0.01.txt](https://github.com/EA31337/EA31337/files/2026368/lot_size_report_0.01.txt)

Not from today, so the balance was 1558 at the time, but nothing has changed otherwise on that account.

**Comment by kenorb** [comment]
That should be enough, thanks, will check that in the evening.

**Comment by kenorb** [comment]
Lot size (when set to 0) in v1.072 is calculated in [`GetLotSizeAuto()`](https://github.com/EA31337/EA31337/blob/v1.072/src/EA31337.mq4#L3822) as:

    double avail_margin = fmin(AccountFreeMargin(), Account::AccountBalance() + Account::AccountCredit());
    double new_lot_size = avail_margin / market_marginrequired * ea_risk_margin/100 * risk_ratio;

So the one with 0.07 is calculated as:

    new_lot_size = 1000.00 (Avail Margin) / 200 (Margin Required) * 1 (Risk margin as 1%) / 100 * 1.0 (Risk Ratio)

which makes 0.05, so not sure why 0.07, but close enough.

--

I'll check the other account shortly.

**Comment by hongguangguo** [comment]
I see  [Trade class CalcLotSize]( https://github.com/EA31337/EA31337-classes/blob/master/Trade.mqh).  I have some questions.
1. why use `_orders_avg`
2.  not use `_risk_margin` , when backtest using mode:lite, advanced.

**Comment by kenorb** [comment]
> * why use `_orders_avg`

It's for further reduction of the overall risk. As each lot size is calculated for individual order, but we don't know how many we're going to open (low or high amount). For example, we could have a type of strategy which opens 1 order in average (_orders_avg=1) then we can allow a higher lot size or another setup with 20 orders, then we need to predict the risk. Basically we need to take into the account amount of orders we're planning to open to protect the account.
Currently _orders_avg is set to 10 by default, but ideally we could have this auto-calculated, like taking the average of maximum orders opened at once for the current week.

> * not use `_risk_margin` , when backtest using mode:lite, advanced.

Risk margin has been used in EA v1.xxx versions, the logic is going to be re-added at some point for v2 versions.
